name: React Native CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods (for iOS)
        if: runner.os == 'macOS'
        run: |
          npm install -g pod-install
          pod-install --repo-update

  android:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"

      - name: Build Android
        run: |
          npx react-native run-android --no-jetifier

  ios:
    runs-on: macos-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods dependencies
        run: pod install --project-directory=ios

      - name: Build iOS
        run: xcodebuild -workspace ios/Agile.xcworkspace -scheme Agile -sdk iphonesimulator -configuration Release clean build

  test:
    runs-on: ubuntu-latest
    needs: [android, ios]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run tests
        run: npm test
